# Generated by Django 5.2 on 2025-04-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_verifytoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verifytoken',
            name='user',
        ),
        migrations.AddField(
            model_name='verifytoken',
            name='user_id',
            field=models.UUIDField(default=1, editable=False),
            preserve_default=False,
        ),
    ]
